// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateJobListingInput struct {
	Title       string  `json:"title"`
	Description string  `json:"description"`
	Company     string  `json:"company"`
	URL         *string `json:"url"`
}

type DeleteJobResponse struct {
	DeleteJobID string `json:"deleteJobId"`
}

type JobListing struct {
	ID          string  `json:"_id" bson:"_id,omitempty"`
	Title       string  `json:"title"`
	Description string  `json:"description"`
	Company     string  `json:"company"`
	URL         *string `json:"url"`
}

type UpdateJobListingInput struct {
	Title       *string `json:"title"`
	Description *string `json:"description"`
	URL         *string `json:"url"`
}
